// swift-tools-version:5.9
// Generated by scripts/release/swift-dist.mjs from packages/ios-openai at version 0.1.0-beta.2.
// Don't edit here: change the monorepo and release again.
import PackageDescription

// The native OpenAI Realtime VoiceSource over WebRTC (docs/audio-pipeline.md,
// *Native OpenAI Realtime*). Its own package, like packages/ios-livekit: it
// carries a WebRTC binary that SinuaView and the other vendors must never pull.
// WebRTC is LiveKit's prefixed build -- `from:` the version client-sdk-swift
// 2.17.0 pins exactly, so an app with both resolves to one binary.
let package = Package(
    name: "SinuaOpenAI",
    platforms: [.iOS(.v15)],
    products: [
        .library(name: "SinuaOpenAI", targets: ["SinuaOpenAI"])
    ],
    dependencies: [
        .package(url: "https://github.com/sinua-dev/sinua-swift", exact: "0.1.0-beta.2"),
        .package(url: "https://github.com/livekit/webrtc-xcframework.git", from: "150.7871.02"),
    ],
    targets: [
        .target(
            name: "SinuaOpenAI",
            dependencies: [
                .product(name: "SinuaVoice", package: "sinua-swift"),
                .product(name: "LiveKitWebRTC", package: "webrtc-xcframework"),
            ],
            path: "Sources/SinuaOpenAI"
        )
    ]
)
